version: "3"
services:
  postgres:
    image: "postgres:latest"

  redis:
    image: "redis:latest"

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"

  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules/
      - ./server:/app
    environment:
      - PG_DB=postgres
      - PG_HOST=postgres
      - PG_PASS=postgres_password
      - PG_PORT=5432
      - PG_USER=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
